### ISSUE TITLE
READ_PHONE_STATE permission - how to remove

### ISSUE THREAD

**Issue by dri-richard** [AGulev/defold-extension-appsflyer#5]
I added DefAppsFlyer to our game recently and uploaded a new build to the Google Play Console, where it warned about the READ_PHONE_STATE permission.
I see a comment in AndroidManifest.xml that it's 'optional' but I'm not sure how to remove it - I'm not an Android expert at all, but I understand that READ_PHONE_STATE is considered a little invasive.

**Comment by AGulev** [comment]
fixed in 0.4.1
https://github.com/AGulev/DefAppsFlyer/releases/tag/0.4.1
