### ISSUE TITLE
Reinstate iOS support

### ISSUE THREAD

**Issue by dri-richard** [AGulev/defold-extension-appsflyer#7]
iOS support has been missing since the refactor.
One [fork](https://github.com/HGPoint/defold-extension-appsflyer) has it, but I had some issues building with it.

**Comment by AGulev** [comment]
@dri-richard you have to use two dependencies at the same time:
https://github.com/SalavatR/def_appsflyer_ad_revenue/archive/refs/tags/6.9.0.zip
https://github.com/HGPoint/defold-extension-appsflyer/archive/refs/tags/6.10.2.zip

**Comment by dri-richard** [comment]
That give me errors when I build in editor (1.4.5)
We're putting a release build together today so I'll have to look later.
<img width="1018" alt="image" src="https://github.com/AGulev/defold-extension-appsflyer/assets/26457985/4a4f387b-1c0f-409f-a9a2-913c2c6eb91d">
